name: build
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'images/**/Dockerfile*'

jobs:
  control:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.collect.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Collect changed Dockerfiles
        id: collect
        run: |
          git fetch origin ${{ github.ref_name }} --depth=1
          DIFF=$(git diff --name-only origin/${{ github.ref_name }} HEAD | grep --color=never Dockerfile || echo "")
          echo "=====diffs====="
          echo "${DIFF}"
          echo "==============="
          TARGETS=$(echo "${DIFF}" | awk -v ORS="" 'BEGIN { print "[" } NR==1 { print $0 } NR >1 { print "," $0 } END { print "]" }')
          echo "targets=${TARGETS}" >> "GITHUB_OUTPUT"

  build:
    needs: control
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        target: ${{ needs.control.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      
      - name: Build and push
        run: |
          DIR=$(dirname "${{ matrix.target }}")
          FILENAME=(basename "${{ matrix.target }}")
          IMAGE_NAME="satysfi-$(realpath --relative-to="images" | sed "s|/|-|")"
          TAG=$((echo "$FILENAME" | grep --color=never -o -e "\..*$") || echo "latest")
          FULLNAME="ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$TAG"
          
          echo "build ${{ matrix.target }} as $IMAGE_NAME:$TAG"

          docker build -f "${{ matrix.target }}" -t "$FULLNAME" "$DIR"
          docker push "$FULLNAME"