name: build
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'images/**'
      - '!images/**/README.md'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["ubuntu", "alpine"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: satysfi-${{ matrix.distro }}-buildx-${{ hashFiles('**/*.Dockerfile') }}
          restore-keys: |
            satysfi-${{ matrix.distro }}-buildx-
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      - name: Build and push
        run: deno run -A build.ts --base=${{ matrix.distro }}

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache     
