name: schedule
on:
  workflow_dispatch:
    inputs:
      mode:
        description: running mode
        required: true
        default: "all"
        type: choice
        options:
          - all
          - diff
  push:
    branches:
      - 'main'
    paths:
      - 'images/**/Dockerfile*'

env:
  DELIM: ━─━─━─━─━─━
  TARGETS:

jobs:
  entry:
    runs-on: ubuntu-latest
    outputs:
      mode: ${{ steps.coalesce.outputs.MODE }}
    steps:
      - id: coalesce
        run: |
          MODE="${{ inputs.mode || 'diff' }}"
          echo "MODE=${MODE}" >> "$GITHUB_OUTPUT"

  all:
    runs-on: ubuntu-latest
    needs: entry
    if: ${{ needs.entry.outputs.mode == 'all' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect all Dockerfiles
        run: |
          FILES=$(find ./images -wholename **/Dockerfile*)
          echo "=====files====="
          echo "${FILES}"
          echo "==============="
          echo "TARGETS<<${{ env.DELIM }}" >> "$GITHUB_ENV"
          echo "${FILES}" >> "$GITHUB_ENV"
          echo "${{ env.DELIM }}" >> "$GITHUB_ENV"

      - uses: .github/workflows/build.yml
        with:
          targets: ${{ env.TARGETS }}

  diff:
    runs-on: ubuntu-latest
    needs: entry
    if: ${{ needs.entry.outputs.mode == 'diff' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Collect changed Dockerfiles
        run: |
          git fetch origin ${{ github.ref_name }} --depth=1
          DIFF=$(git diff --name-only origin/${{ github.ref_name }} HEAD | grep --color=never Dockerfile || echo "")
          echo "=====diffs====="
          echo "${DIFF}"
          echo "==============="
          echo "TARGETS<<${{ env.DELIM }}" >> "$GITHUB_ENV"
          echo "${DIFF}" >> "$GITHUB_ENV"
          echo "${{ env.DELIM }}" >> "$GITHUB_ENV"
        
      - uses: .github/workflows/build.yml
        with:
          targets: ${{ env.TARGETS }}